/* Generated by CIL v. 1.5.1 */
/* print_CIL_Input is true */

#line 339 "/usr/include/stdio.h"
extern int printf(char const   * __restrict  __format  , ...) ;
#line 16 "../test/yufeitest/onlyc.c"
extern int ( /* missing proto */  strcpy)() ;
#line 17
extern int ( /* missing proto */  strlen)() ;
#line 20
extern int ( /* missing proto */  atoi)() ;
#line 4 "../test/yufeitest/onlyc.c"
int main(int argc , char **argv ) 
{ 
  char expression[1024] ;
  char *e ;
  char *program ;
  int n ;
  char *tmp ;
  int tmp___0 ;
  int input ;
  int tmp___1 ;
  char **mem_12 ;
  char **mem_13 ;
  int __retres14 ;

  {
#line 6
  e = expression;
#line 7
  mem_12 = argv + 0;
#line 7
  program = *mem_12;
#line 13
  n = 1;
  {
#line 13
  while (1) {
    while_continue: /* CIL Label */ ;
#line 13
    if (n < argc) {

    } else {
#line 13
      goto while_break;
    }
#line 14
    if (n != 1) {
#line 15
      tmp = e;
#line 15
      e ++;
#line 15
      *tmp = (char )' ';
    } else {

    }
#line 16
    mem_13 = argv + n;
#line 16
    strcpy(e, *mem_13);
#line 17
    tmp___0 = strlen(e);
#line 17
    e += tmp___0;
#line 13
    n ++;
  }
  while_break: /* CIL Label */ ;
  }
#line 20
  tmp___1 = atoi(expression);
#line 20
  input = tmp___1;
#line 21
  if (input > 10) {
#line 22
    printf((char const   * __restrict  )"%d\n", 1);
  } else
#line 23
  if (input <= 10) {
#line 24
    printf((char const   * __restrict  )"%d\n", 0);
  } else {

  }
#line 27
  __retres14 = 0;
#line 4
  return (__retres14);
}
}
